baseURL = "https://127.0.0.1/"
timeZone = "Asia/Shanghai"

defaultContentLanguage = "zh-cn"
defaultContentLanguageInSubdir = false
[languages]
  [languages.zh-cn]
    contentDir = "content/zh-cn"
    languageCode = "zh-CN"
    languageName = "中文"
    title = "Wang的个人站点"
    weight = 1
    [languages.zh-cn.pagination]
      disableAliases = false
      pagerSize = 5
      path = "page"
    [languages.zh-cn.Params]
      description = "站点描述"
      subtitle = "比较长的子标题"

  [languages.en-us]
    contentDir = "content/en-us"
    languageCode = "en-US"
    languageName = "English"
    title = "Wang's site"
    weight = 2
    [languages.en-us.pagination]
      disableAliases = false
      pagerSize = 5
      path = "page"
    [languages.en-us.Params]
      description = "desc"
      subtitle = "subtitle"

[outputFormats]
  [outputFormats.search_index]
    name = "json"
    mediaType = "application/json"
    baseName = "search_index"
    isPlainText = true
    notAlternative = true
  [outputFormats.year_month_index]
    name = "json"
    mediaType = "application/json"
    baseName = "year_month_index"
    isPlainText = true
    notAlternative = true
  [outputFormats.post_day_mark]
    name = "json"
    mediaType = "application/json"
    baseName = "post_day_mark"
    isPlainText = true
    notAlternative = true

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  archives = "archives"

[params]
  mainSections = ["posts"]  # mainSections下的文档会用于生成search_index.json, 用来文章检索
  math = false  # 默认关闭mathjax支持, 需要的话在Front Matter打开
  enable_giscus = true  # 是否启用github评论功能

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]
