[[main]]
  name = "首页"
  pageRef = "/"
  weight = 100
[[main]]
  name = "文章"
  pageRef = "/posts/"
  weight = 200
[[main]]
  name = "照片墙"
  pageRef = "/gallery/"
  weight = 300
[[main]]
  name = "在线工具"
  pageRef = "/tools/"
  weight = 400
[[main]]
  name = "关于本站"
  pageRef = "/about/"
  weight = 500
