[[main]]
  name = "Home"
  pageRef = "/"
  weight = 100
[[main]]
  name = "Posts"
  pageRef = "/posts/"
  weight = 200
[[main]]
  name = "Gallery"
  pageRef = "/gallery/"
  weight = 300
[[main]]
  name = "Gadgets"
  pageRef = "/tools/"
  weight = 400
[[main]]
  name = "About"
  pageRef = "/about/"
  weight = 500
